"""add paystack finance ledger

Revision ID: 74830cffdf61
Revises: d41a3c8e9b27
Create Date: 2026-05-19 13:13:24.789128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74830cffdf61'
down_revision: Union[str, None] = 'd41a3c8e9b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('event_digest', sa.String(length=128), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('signature', sa.String(length=160), nullable=True),
    sa.Column('processing_status', sa.String(length=30), server_default='received', nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_webhook_events_event_digest'), 'payment_webhook_events', ['event_digest'], unique=True)
    op.create_index(op.f('ix_payment_webhook_events_event_type'), 'payment_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_webhook_events_processing_status'), 'payment_webhook_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_payment_webhook_events_provider'), 'payment_webhook_events', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_webhook_events_reference'), 'payment_webhook_events', ['reference'], unique=False)
    op.create_table('platform_treasury_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='GHS', nullable=False),
    sa.Column('current_balance', sa.Float(), server_default='0', nullable=False),
    sa.Column('vendor_liability_balance', sa.Float(), server_default='0', nullable=False),
    sa.Column('commission_balance', sa.Float(), server_default='0', nullable=False),
    sa.Column('gross_collected_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('processor_fee_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('refunded_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('total_payouts_sent', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_treasury_accounts_currency'), 'platform_treasury_accounts', ['currency'], unique=True)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), server_default='paystack', nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('access_code', sa.String(length=120), nullable=True),
    sa.Column('authorization_url', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='GHS', nullable=False),
    sa.Column('amount_subunit', sa.Integer(), nullable=False),
    sa.Column('processor_fee_subunit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='initialized', nullable=False),
    sa.Column('preferred_channel', sa.String(length=40), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=80), nullable=True),
    sa.Column('gateway_response', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorization_data', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_provider'), 'payment_transactions', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_transactions_provider_transaction_id'), 'payment_transactions', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_reference'), 'payment_transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_table('platform_ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('payment_transaction_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('return_request_id', sa.UUID(), nullable=True),
    sa.Column('vendor_withdrawal_request_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('current_balance_after', sa.Float(), nullable=False),
    sa.Column('vendor_liability_balance_after', sa.Float(), nullable=False),
    sa.Column('commission_balance_after', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['treasury_account_id'], ['platform_treasury_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_withdrawal_request_id'], ['vendor_withdrawal_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_transaction_id', 'kind', name='uq_platform_ledger_payment_kind'),
    sa.UniqueConstraint('return_request_id', 'kind', name='uq_platform_ledger_return_kind'),
    sa.UniqueConstraint('vendor_withdrawal_request_id', 'kind', name='uq_platform_ledger_withdrawal_kind')
    )
    op.create_index(op.f('ix_platform_ledger_entries_kind'), 'platform_ledger_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_platform_ledger_entries_order_id'), 'platform_ledger_entries', ['order_id'], unique=False)
    op.create_index(op.f('ix_platform_ledger_entries_payment_transaction_id'), 'platform_ledger_entries', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_platform_ledger_entries_return_request_id'), 'platform_ledger_entries', ['return_request_id'], unique=False)
    op.create_index(op.f('ix_platform_ledger_entries_treasury_account_id'), 'platform_ledger_entries', ['treasury_account_id'], unique=False)
    op.create_index(op.f('ix_platform_ledger_entries_vendor_withdrawal_request_id'), 'platform_ledger_entries', ['vendor_withdrawal_request_id'], unique=False)
    op.add_column('orders', sa.Column('payment_status', sa.String(length=30), server_default='pending', nullable=False))
    op.add_column('orders', sa.Column('payment_provider', sa.String(length=30), server_default='paystack', nullable=False))
    op.add_column('orders', sa.Column('payment_reference', sa.String(length=80), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orders_payment_provider'), 'orders', ['payment_provider'], unique=False)
    op.create_index(op.f('ix_orders_payment_reference'), 'orders', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.execute(
        """
        UPDATE orders
        SET
            payment_status = CASE
                WHEN status = 'cancelled' THEN 'refunded'
                ELSE 'paid'
            END,
            payment_provider = CASE
                WHEN status = 'pending_payment' THEN 'paystack'
                ELSE 'manual'
            END,
            paid_at = CASE
                WHEN status <> 'cancelled' THEN placed_at
                ELSE paid_at
            END,
            refunded_at = CASE
                WHEN status = 'cancelled' THEN cancelled_at
                ELSE refunded_at
            END
        WHERE status <> 'pending_payment'
        """
    )
    op.alter_column('orders', 'status', server_default='pending_payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voucher_redemptions_order_id'), table_name='voucher_redemptions')
    op.create_index(op.f('ix_voucher_redemptions_order_id'), 'voucher_redemptions', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('voucher_redemptions_order_id_key'), 'voucher_redemptions', ['order_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('vendor_wallets_vendor_user_id_key'), 'vendor_wallets', ['vendor_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_reference'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_provider'), table_name='orders')
    op.drop_column('orders', 'refunded_at')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'payment_reference')
    op.drop_column('orders', 'payment_provider')
    op.drop_column('orders', 'payment_status')
    op.alter_column('orders', 'status', server_default='processing')
    op.drop_index(op.f('ix_platform_ledger_entries_vendor_withdrawal_request_id'), table_name='platform_ledger_entries')
    op.drop_index(op.f('ix_platform_ledger_entries_treasury_account_id'), table_name='platform_ledger_entries')
    op.drop_index(op.f('ix_platform_ledger_entries_return_request_id'), table_name='platform_ledger_entries')
    op.drop_index(op.f('ix_platform_ledger_entries_payment_transaction_id'), table_name='platform_ledger_entries')
    op.drop_index(op.f('ix_platform_ledger_entries_order_id'), table_name='platform_ledger_entries')
    op.drop_index(op.f('ix_platform_ledger_entries_kind'), table_name='platform_ledger_entries')
    op.drop_table('platform_ledger_entries')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_reference'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_provider_transaction_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_provider'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_platform_treasury_accounts_currency'), table_name='platform_treasury_accounts')
    op.drop_table('platform_treasury_accounts')
    op.drop_index(op.f('ix_payment_webhook_events_reference'), table_name='payment_webhook_events')
    op.drop_index(op.f('ix_payment_webhook_events_provider'), table_name='payment_webhook_events')
    op.drop_index(op.f('ix_payment_webhook_events_processing_status'), table_name='payment_webhook_events')
    op.drop_index(op.f('ix_payment_webhook_events_event_type'), table_name='payment_webhook_events')
    op.drop_index(op.f('ix_payment_webhook_events_event_digest'), table_name='payment_webhook_events')
    op.drop_table('payment_webhook_events')
    # ### end Alembic commands ###
