ODOS_CATEGORY_TAXONOMY = [
    {
        "slug": "fashion",
        "title": "Fashion",
        "subtitle": "Style-forward clothing, accessories, and curated looks for every shopper.",
        "image_key": "dress",
        "subcategories": [
            "Ladies Wear",
            "Men’s Wear",
            "Kids Wear",
            "Shoes",
            "Bags",
            "Watches",
            "Jewelry",
            "Traditional Wear",
            "Underwear",
            "Sportswear",
            "Beauty Accessories",
        ],
    },
    {
        "slug": "shoes-footwear",
        "title": "Shoes & Footwear",
        "subtitle": "Everyday, occasion, and performance footwear across all ages.",
        "image_key": "shoe5",
        "subcategories": [
            "Sneakers",
            "Sandals",
            "Slippers",
            "Heels",
            "Boots",
            "School Shoes",
            "Men’s Shoes",
            "Ladies Shoes",
            "Kids Shoes",
        ],
    },
    {
        "slug": "phones-electronics",
        "title": "Phones & Electronics",
        "subtitle": "Devices, accessories, and digital essentials for work and play.",
        "image_key": "headset",
        "subcategories": [
            "Smartphones",
            "Tablets",
            "Laptops",
            "Desktop Computers",
            "Smart Watches",
            "Phone Accessories",
            "Chargers",
            "Earbuds & Headphones",
            "Speakers",
            "Gaming Consoles",
            "Cameras",
        ],
    },
    {
        "slug": "home-living",
        "title": "Home & Living",
        "subtitle": "Practical and beautiful essentials for daily home life.",
        "image_key": "bag",
        "subcategories": [
            "Furniture",
            "Kitchen Appliances",
            "Cookware",
            "Home Decor",
            "Bedding",
            "Curtains",
            "Cleaning Supplies",
            "Lighting",
            "Storage & Organization",
        ],
    },
    {
        "slug": "groceries-food",
        "title": "Groceries & Food",
        "subtitle": "Staples, fresh items, snacks, and pantry-ready household food needs.",
        "image_key": "bag",
        "subcategories": [
            "Fresh Food",
            "Vegetables",
            "Fruits",
            "Rice & Grains",
            "Cooking Oil",
            "Drinks",
            "Snacks",
            "Frozen Foods",
            "Local Foodstuff",
            "Bakery",
        ],
    },
    {
        "slug": "beauty-personal-care",
        "title": "Beauty & Personal Care",
        "subtitle": "Skincare, grooming, cosmetics, and self-care essentials.",
        "image_key": "cosmetics",
        "subcategories": [
            "Makeup",
            "Skincare",
            "Hair Products",
            "Perfumes",
            "Barbershop Supplies",
            "Salon Supplies",
            "Soaps",
            "Creams",
            "Wigs & Extensions",
        ],
    },
    {
        "slug": "baby-products",
        "title": "Baby Products",
        "subtitle": "Trusted everyday picks for infant care, feeding, and comfort.",
        "image_key": "sports",
        "subcategories": [
            "Baby Clothing",
            "Diapers",
            "Baby Food",
            "Baby Toys",
            "Baby Care",
            "Baby Accessories",
        ],
    },
    {
        "slug": "kids-toys",
        "title": "Kids & Toys",
        "subtitle": "Fun, learning, and school-ready products for growing children.",
        "image_key": "sports",
        "subcategories": [
            "Toys",
            "School Bags",
            "Educational Toys",
            "Bicycles",
            "Kids Accessories",
            "Video Games",
        ],
    },
    {
        "slug": "sports-fitness",
        "title": "Sports & Fitness",
        "subtitle": "Performance gear and active-lifestyle essentials for every routine.",
        "image_key": "sports",
        "subcategories": [
            "Gym Equipment",
            "Jerseys",
            "Football Boots",
            "Exercise Accessories",
            "Sportswear",
            "Outdoor Equipment",
        ],
    },
    {
        "slug": "automobile",
        "title": "Automobile",
        "subtitle": "Vehicle parts, upgrades, and maintenance products for road readiness.",
        "image_key": "automotive",
        "subcategories": [
            "Car Accessories",
            "Car Parts",
            "Motorbike Parts",
            "Tires",
            "Car Care",
            "Oils & Lubricants",
        ],
    },
    {
        "slug": "hardware-tools",
        "title": "Hardware & Tools",
        "subtitle": "Construction, repair, and workshop supplies for serious utility.",
        "image_key": "bag",
        "subcategories": [
            "Power Tools",
            "Plumbing",
            "Electricals",
            "Building Materials",
            "Hand Tools",
            "Paint Supplies",
        ],
    },
    {
        "slug": "books-stationery",
        "title": "Books & Stationery",
        "subtitle": "Learning, office, and school supplies for focused daily productivity.",
        "image_key": "backpack1",
        "subcategories": [
            "Textbooks",
            "Novels",
            "Office Supplies",
            "School Supplies",
            "Printing Materials",
        ],
    },
]
